title = "template-web"
description = ""
version = "0.1.0"
license = "MIT"
main = "src/main.clio"
authors = [ "Your Name <you@example.com>" ]
keywords = ""

[build]
directory = "build"
target = "web"

[target.web]
directory = "src"
target = "web"

[scripts]
test = "No tests specified"

[dependencies]
stdlib = "latest"
